#!/usr/bin/env python

from bugzilla.agents import BMOAgent
import subprocess
import colorama
from colorama import Fore, Style

if __name__ == '__main__':
    colorama.init()

    username = subprocess.check_output('git config user.email', shell=True)
    bmo = BMOAgent(username, None)

    options = {
        'email1':             username,
        'email1_assigned_to': 1,
        'status':             'NEW'
    }

    buglist = []
    status = ['NEW', 'REOPENED']
    for s in status:
        options['status'] = s
        buglist.extend(bmo.get_bug_list(options))

    for bug in buglist:
        print(Fore.GREEN + Style.BRIGHT + str(bug.id) + Style.RESET_ALL),
        print('- ' + bug.summary)
